# Generated by Django 3.2.8 on 2021-10-06 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_tag_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='link',
            field=models.URLField(default=''),
        ),
    ]
