# Generated by Django 3.2.8 on 2021-10-06 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_user_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='position',
            name='offer_education_id',
        ),
        migrations.AddField(
            model_name='position',
            name='offer_education',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
