# Generated by Django 3.2.8 on 2021-10-06 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20211006_2306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='position',
            name='operating_schedule_id',
        ),
        migrations.AddField(
            model_name='position',
            name='operating_schedule',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
