# Generated by Django 3.2.8 on 2021-10-07 01:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20211006_2312'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='predicted_tag',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.tag'),
        ),
    ]
