# Generated by Django 3.2.8 on 2021-10-07 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_position_predicted_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='link',
        ),
        migrations.AddField(
            model_name='position',
            name='link',
            field=models.URLField(default=''),
        ),
    ]
