# Generated by Django 3.2.8 on 2021-10-07 12:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20211007_0140'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='messages_count_per_day',
            new_name='days_interval',
        ),
        migrations.AddField(
            model_name='user',
            name='last_pong',
            field=models.DateField(default=datetime.datetime(2021, 6, 29, 16, 46, 55, 964700)),
        ),
    ]
